"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/header";
import Head from "next/head";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { RefObject, useRef } from "react";
import HomePage from "./page";
import {useRouter} from "next/router"
const inter = Inter({ subsets: ["latin"] });



// export const metadata: Metadata = {
//   title: "My Portfolio ",
//   description: "Generated by Patarapong Charoenpol",
//   // icons: [
//   //   {
//   //     rel: "icon",
//   //     href: "./favicon.ico",
//   //     url: "./favicon.ico", // Add the missing url property
//   //   },
//   // ],
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const router = useRouter();


  const ScrollDownRef = useRef<HTMLDivElement>(null);

  const scrollToItem = (index: number) => {
    const container = ScrollDownRef.current;
    if (container) {
      const item = container.children[index] as HTMLElement;
      console.log(item.offsetTop);
      window.scrollTo({
        top: item.offsetTop,
        behavior: 'smooth',

      });

    }
  };

  const RenderChildrenOrPage = () => {
    if (window.location.pathname === "/") {
      return <HomePage ScrollDownRef={ScrollDownRef}   />;
    } else {
      return children;
    }
  }



  
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>My Portfolio</title>
        <meta name="description" content={"Generated by Patarapong Charoenpol"} />
        <link rel="shortcut icon" href="/icons/favicon.ico" sizes="14" />
      </Head>
      <body className={inter.className}>
        <SpeedInsights />
        <div className=" relative ">
          <div className=" sticky top-0 z-[999] w-full">
            <Header scrollToItem= {scrollToItem}/>
          </div>
          {RenderChildrenOrPage()}
        </div>

      </body>
    </html>
  );
}
